### ISSUE TITLE
"Here's" link toward bottom of page leads to "does not exist" message

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/formal-affair-rails#4]
I'd fix this if I could, but I'm not sure where the link is supposed to go.

The link is right above the "Deliverables" section on the word "Here's".

**Comment by AnnJohn** [comment]
Thanks @garettarrowood for raising the issue. We're not yet up to the reviewing our Rails curriculum so for now, I'm going to remove the link altogether and icebox this issue until we get to reviewing that portion of the track.

**Comment by AnnJohn** [comment]
As a temporary fix, removed the link altogether but when reviewing the curriculum please update. Here's the broken link below:

[Here's](http://news-anand.blogspot.com/2013/05/include-csrf-token-in-form-ruby-on-rails.html)
an example of how to do so.
